# Generated by Django 2.1.7 on 2019-03-02 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('unity_cost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('unity', models.CharField(max_length=20)),
            ],
        ),
    ]
